### ISSUE TITLE
Enable Processing a Batch of Images

### ISSUE THREAD

**Issue by 0xhephaistos** [GreenLandisaLie/AuraSR-ComfyUI#12]
Hi there,

Thank you for your great work such as the fast implementation of the newest model version.

I just tinkered with it and it seems as that the node cannot handle images batches.
Would it be possible for you to integrate this functionality, so I can use it to batch upscale images?

Or am I doing something wrong?

**Comment by GreenLandisaLie** [comment]
Added batch support starting from v3.0.0.

Please open a new issue if you find any bugs - it's highly untested but seems to be working.
