### ISSUE TITLE
Cannot select the "model_name" in the "AuraSR Upscaler" node.

### ISSUE THREAD

**Issue by Willy-Shenn** [GreenLandisaLie/AuraSR-ComfyUI#13]
Hello, I'm sorry, but when using this node, I followed your instructions to install and place the relevant model in the specified location. However, the node option "model_name" is not selectable; it only allows selection between "null" and "undefined." When I use the node with the right mouse button, no menu appears. Once I select "undefined," I can't make any selections. I also tried customizing the path in the extra_model_paths.yaml file, but it didn't change anything. However, I did rename the model and its .json file. Detailed images are provided below. I would greatly appreciate your guidance on resolving this issue.
![螢幕擷取畫面 2024-08-04 001454](https://github.com/user-attachments/assets/fa286625-33a9-4daa-b2d4-1c1d42b6e5fc)
![螢幕擷取畫面 2024-08-04 000412](https://github.com/user-attachments/assets/aeede50a-447a-4f27-9d7e-4ced8980664b)
![螢幕擷取畫面 2024-08-04 001118](https://github.com/user-attachments/assets/6ece3bd2-5af6-4ee8-8d40-583a0d22bf15)

**Comment by GreenLandisaLie** [comment]
Hi.

If you don't need to specify custom locations in ComfyUI, you don't need to use the 'extra_model_paths.yaml' file at all. 

Another thing, you have '**path/to/comfyui/**' in your **base_path** - which is not an actual path and if left like that you will get that problem. Are you really using the file as shown in the screenshots? If so, then that's the problem. You can either not use the 'extra_model_paths.yaml' file or point the base_path to your actual ComfyUI location like so:

**base_path: D:/Stable-Diffusion/ComfyUI/ComfyUI**

**Comment by GreenLandisaLie** [comment]
I found another issue with your setup. 

You named the models 'Aura-SR v1 model.safetensors' and 'Aura-SR v2 model.safetensors' - which is ok, you can name them whatever you want. But to have separate config files - one for each model version - you need to name the config file exactly the same as the model's themselves. 
So, in your case, you would need to name the config files like so: 'Aura-SR v1 model.json' and 'Aura-SR v2 model.json'.

The selection logic for config files is as follows:
- if a 'modelName.json' file exists in the same directory as the model itself and the model is also named as 'modelName' - then that's the config file that will be used for that model.
- if no 'modelName.json' file is found, then the node will attempt to find a (**literally named**) 'config.json' file at the model's location (which can be a subdirectory within Aura-SR root folder).
- if after both attempts above no config file was detected - the node will attempt to find a (**literally named**) 'config.json' file at Aura-SR's root location - and if found, it will use that one and give you a warning saying that config file might not be appropriate for whatever non-root located Aura-SR model you specified.

**Comment by Willy-Shenn** [comment]
> 你好。
> 
> 如果您不需要在 ComfyUI 中指定自訂位置，則根本不需要使用「extra_model_paths.yaml」檔案。
> 
> 另一件事，你的**base_path**中有' **path/to/comfyui/** ' - 這不是一個實際的路徑，如果這樣的話你會遇到這個問題。您真的使用螢幕截圖中所示的文件嗎？如果是這樣，那就是問題所在。您可以不使用「extra_model_paths.yaml」文件，也可以將 base_path 指向您的實際 ComfyUI 位置，如下所示：****
> 
> **基本路徑：D：/穩定擴散/ComfyUI/ComfyUI**
> 
> 編輯：它是 ofc，也可以為“extra_model_paths”檔案中的任何條目提供完整路徑，如下所示：
> 
> **aura-sr：D：/穩定擴散/ComfyUI/ComfyUI/models/Aura-SR**

Sorry, I have already commented out (#) the path issue. The image was selected incorrectly, so I will delete the custom path and use the default path instead.

**Comment by Willy-Shenn** [comment]
> 我發現您的設定有另一個問題。
> 
> 您將模型命名為“Aura-SR v1 model.safetensors”和“Aura-SR v2 model.safetensors” - 沒關係，您可以將它們命名為任何您想要的名稱。但是要擁有單獨的設定檔（每個模型版本一個），您需要將設定檔命名為與模型本身完全相同的名稱。 因此，在您的情況下，您需要將設定檔命名為：「Aura-SR v1 model.json」和「Aura-SR v2 model.json」。
> 
> 設定檔的選擇邏輯如下：
> 
> * 如果「modelName.json」檔案與模型本身位於同一目錄中，而該模型也被命名為「modelName」 - 那麼這就是將用於該模型的設定檔。
> * 如果未找到“modelName.json”文件，則節點將嘗試在模型位置（可以是 Aura-SR 根資料夾中的子目錄）查找（**字面命名）“config.json”文件。**
> * 如果在上述兩次嘗試後都沒有檢測到配置文件 - 節點將嘗試在 Aura-SR 的根位置查找一個（**字面命名的**）“config.json”文件- 如果找到，它將使用該文件並向您發出警告該設定檔可能不適用於您指定的任何非根位置的 Aura-SR 模型。

Yes, following your instructions, it worked! Thank you so much for your time.

**Comment by Willy-Shenn** [comment]
> > 我發現您的設定有另一個問題。
> > 您將模型命名為“Aura-SR v1 model.safetensors”和“Aura-SR v2 model.safetensors” - 沒關係，您可以將它們命名為任何您想要的名稱。但是要擁有單獨的設定檔（每個模型版本一個），您需要將設定檔命名為與模型本身完全相同的名稱。 因此，在您的情況下，您需要將設定檔命名為：「Aura-SR v1 model.json」和「Aura-SR v2 model.json」。
> > 設定檔的選擇邏輯如下：
> > 
> > * 如果「modelName.json」檔案與模型本身位於同一目錄中，而該模型也被命名為「modelName」 - 那麼這就是將用於該模型的設定檔。
> > * 如果未找到“modelName.json”文件，則節點將嘗試在模型位置（可以是 Aura-SR 根資料夾中的子目錄）查找（**字面命名）“config.json”文件。**
> > * 如果在上述兩次嘗試後都沒有檢測到配置文件 - 節點將嘗試在 Aura-SR 的根位置查找一個（**字面命名的**）“config.json”文件- 如果找到，它將使用該文件並向您發出警告該設定檔可能不適用於您指定的任何非根位置的 Aura-SR 模型。
> 
> Yes, following your instructions, it worked! Thank you so much for your time.

Sorry, I’m not very skilled with software, and I apologize for any inconvenience I may have caused you.
