### ISSUE TITLE
Upscale not work

### ISSUE THREAD

**Issue by Aljnk** [GreenLandisaLie/AuraSR-ComfyUI#4]
I tried your node but nothing happened - 

<img width="985" alt="Screenshot_1" src="https://github.com/GreenLandisaLie/AuraSR-ComfyUI/assets/11256478/37167ed5-af68-4f58-811c-647d994bf545">

After your node images have equal sizes

**Comment by kakachiex2** [comment]
Same problem here same size and detail and not option for upscaling 2x | 4x etc...

**Comment by kakachiex2** [comment]
And the upscaled image is smaller in size

**Comment by kakachiex2** [comment]
Solution you need to add the jason file in the AuraSR folder and it works

**Comment by GreenLandisaLie** [comment]
You will get the same input when something wrong has happened - in which case you should see info about the error in your terminal. I chose this approach over returning an actual error and freeze the rest of your workflow.

Please try running it again, check your terminal and tell me what error you got.

> [kakachiex2](https://github.com/kakachiex2) Solution you need to add the jason file in the AuraSR folder and it works

Yeah its stated in the 'Instructions' section and you also get a warning about it in your terminal.

**Comment by GreenLandisaLie** [comment]
Closing this under the assumption the user was just missing the required config.json file.

**Comment by supergaozx** [comment]
1) Require config.json file
2) Don't change config.json 's name
