### ISSUE TITLE
Tiling problem

### ISSUE THREAD

**Issue by valtersgrauzins** [GreenLandisaLie/AuraSR-ComfyUI#7]
I am testing AuraSR-ComfyUI. And i am facing tiling problem. Upscaling works in one fixed square size, which causes very noticeable tiling problems. Is this problem is planned to solve?
![PrtSc23_07](https://github.com/user-attachments/assets/7bf97c23-3286-41a8-a2d2-90b71f206f5b)

**Comment by GreenLandisaLie** [comment]
This repo is just an implementation of AuraSR to ComfyUI. You would have to contact the devs of AuraSR directly to fix that.

I've encountered this issue and noticed that the more compressed the input image is - the more noticeable the tiles become. You can compare my test results here: [https://imgsli.com/Mjc1NzYw/0/2](https://imgsli.com/Mjc1NzYw/0/2) (notice how visible the tiles are around the statue's right leg in the 'AuraSR' slider and how much better it became when DeJPG was used beforehand). If you zoom in you will still see some remnants of tiles in the DeJPG-to-AuraSR slider but keep in mind the original image was highly compressed to begin with.

Avoid using compressed images and if possible use images straight from AI generation before any saving has occurred - even then, you might still see something but you could always pass the upscaled image back into the AI for refinement which would fix the tiling issues.

**Comment by GreenLandisaLie** [comment]
I've noticed now their main repo has been updated very recently with code that seems to affect tiles.

I'll update this repo to their latest code as soon as I can and hopefully it will mitigate this problem a bit.

**Comment by valtersgrauzins** [comment]
It's realy great that you worked on implementing AuraSR in the ComfyUI environment. GigaGAN project has a very high potential.

I used DeJPG it removes the compressed information that way, the cell that takes the given sector is not forced to use the compression remnants to enlarge it self. 
In sectors where this compression is more, this cell is forced to use the compression information. In this way, all cells together creats big differences if not used DeJPG. 

But the problem is in the very thought of using cells to enlarge the image. As you mentioned, it's devs of AuraSR own problem and I strongly doubt that the problem will be solved by merging these cells with overlap. However, I prefer that these cells change locations in each iteration, that way you don't end up with tiles with or without overlap.

Have a great day!

**Comment by GreenLandisaLie** [comment]
Yeah I wasn't expecting much from the new overlap functions either but in the single test case I tried I couldn't notice the tiles anymore. Unfortunately I don't have a CUDA device and because it runs so slow on the CPU I simply can't test it thoroughly with many images. It does seem to help a little though.
