### ISSUE TITLE
How to use this model?1xDeJPG_OmniSR.pth

### ISSUE THREAD

**Issue by jokero3answer** [GreenLandisaLie/AuraSR-ComfyUI#9]

**Comment by GreenLandisaLie** [comment]
### It is only recommended to use DeJPG when:

- You are loading (already saved, compressed) JPEGs

- You are using AuraSR v1 (first one released)



If your workflow dos not meet those two conditions then you can skip DeJPG.

### As for how to use it:

Load it as an upscale model.

Pass the input image and the loaded DeJPG model to the 'Upscale Image (using model)' and the ouput of that to AuraSR node.

The model itself does not upscale but it was trained with a popular AI upscaling architecture to 'decompress' JPEGs.

There is an example in the description of this github and inside /nodes_preview:
https://github.com/GreenLandisaLie/AuraSR-ComfyUI/blob/main/nodes_preview/pv2.png
